In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# arange is used to create an array. here, 0 is start, 10 is stop, 2 defines a jump 

In [14]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# it creates arrays of n*m dimension. Here, rows=4 and column =5 
# 0. denotes all are floating point numbers

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,11,23)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. ])

# linspace is used to create evenly spaced linear arrays. Here 23 represents total numbers between 0 and 11 including 11

In [26]:
np.random.randint(0,5)

4

# generates random number. here, 0 is inclusive and 5 is exclusive.

In [28]:
np.random.randint(0,25,(3,3))

array([[ 8,  7,  9],
       [ 3, 15, 16],
       [16, 10,  3]])

In [39]:
np.random.seed(20)
arr = np.random.randint(0,50,24)
arr

array([35, 26, 15, 31, 28, 26,  9, 20, 11, 22,  7, 34, 32, 40, 21, 26, 26,
       19, 16, 38, 38, 16, 41, 37])

# seed is used to get exactly same pattern of random numbers everytime

In [40]:
arr.max()

41

# here we can use min, max, mean and so on. argmax is used to give index location of max value.

In [42]:
arr.reshape(4,6)

array([[35, 26, 15, 31, 28, 26],
       [ 9, 20, 11, 22,  7, 34],
       [32, 40, 21, 26, 26, 19],
       [16, 38, 38, 16, 41, 37]])

In [44]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[4,5]

45

# grab single element from array. here row= 4, column=5. i.e value = 45

In [46]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

# here : represents all elements in a row and 1 represents 1st column elements

In [47]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

# slicing  Here, 0:3 grabs elements from 0th row to 2nd row and 0:4 grabs elements from 0th column to 4th column
# here 3rd and 4th row are not included while grabbing elements

In [50]:
mat[6:9,6:9]

array([[66, 67, 68],
       [76, 77, 78],
       [86, 87, 88]])

In [51]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
mat>45

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

# masking Here it gives boolean values

In [57]:
mat[mat>82]

array([83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])